# Generated by Django 5.2.5 on 2025-09-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('person', 'Person')], help_text='Type of user account', max_length=10, null=True),
        ),
    ]
